-- LogOS: a host-minimal Agda library for modular dynamic logic systems synthesized by AI
-- Copyright (C) 2026 AI.IMPACT GmbH
-- SPDX-License-Identifier: GPL-3.0-only

{-# LANGUAGE StrictData #-}

module Metamath.EmitAgdaRuntime
  ( ExportAgdaRuntimeOptions(..)
  , exportAgdaRuntime
  ) where

import Control.Exception (bracket, throwIO)
import Control.Monad (when)
import Data.ByteString (ByteString)
import System.Directory (canonicalizePath, createDirectoryIfMissing)
import System.FilePath
  ( takeBaseName
  , takeDirectory
  , takeExtension
  , (</>)
  )
import System.IO (IOMode (ReadMode), hClose, openBinaryFile)

import Metamath.Artifact (ArtifactHeader (..), readHeader, readSymbolsAt)
import Metamath.Emit.Common
import Metamath.Types (MMError (..))
import Metamath.SetMMSig (setMMSigBlock)

data ExportAgdaRuntimeOptions = ExportAgdaRuntimeOptions
  { roArtifactDir :: !FilePath
  , roEmitAgdaPath :: !FilePath
  , roAgdaModule :: !String
  , roEnvVar :: !String
  , roEmitRunnerPath :: !(Maybe FilePath)
  , roRunnerModule :: !(Maybe String)
  }

exportAgdaRuntime :: ExportAgdaRuntimeOptions -> IO ()
exportAgdaRuntime opts = do
  when (takeExtension (roEmitAgdaPath opts) /= ".agda") $
    throwIO (MMError ("--emit-agda must be a .agda file, got: " <> roEmitAgdaPath opts))

  let outPath = roEmitAgdaPath opts
      outDir = takeDirectory outPath
      outBase = takeBaseName outPath
      hostPath = outDir </> outBase </> "Host.agda"
      hostMod = roAgdaModule opts <> ".Host"

  createDirectoryIfMissing True (takeDirectory outPath)
  createDirectoryIfMissing True (takeDirectory hostPath)
  maybe (pure ()) (createDirectoryIfMissing True . takeDirectory) (roEmitRunnerPath opts)

  -- Embed an absolute default path in the generated module, but allow an env override.
  let dbPath0 = roArtifactDir opts </> "db.mmdb"
  dbPath <- canonicalizePath dbPath0

  bracket (openBinaryFile dbPath ReadMode) hClose $ \h -> do
    hdr <- readHeader h
    syms <- readSymbolsAt h (ahOffsetSymbols hdr)

    writeFile hostPath (renderRuntimeHostModule hostMod opts dbPath)
    writeFile outPath (renderRuntimePortModule hostMod opts dbPath hdr syms)

    case roEmitRunnerPath opts of
      Nothing -> pure ()
      Just outRunner -> do
        let rmod = maybe (roAgdaModule opts <> ".Runner") id (roRunnerModule opts)
        writeFile outRunner (renderRunnerModule rmod (roAgdaModule opts))

renderRuntimePortModule :: String -> ExportAgdaRuntimeOptions -> FilePath -> ArtifactHeader -> [ByteString] -> String
renderRuntimePortModule hostMod opts dbPath hdr syms =
  unlines $
    agdaModuleHeader (roAgdaModule opts) False
    <> [ ""
    , "-- NOTE: This module is intentionally UNSAFE."
    , "-- It turns a compiled Metamath artifact (`db.mmdb`) into a `LogOS.Ports.Metamath.Database`."
    , "--"
    , "-- Architecture:"
    , "-- - " <> hostMod <> " is the explicit GHC FFI boundary (builtin types only)."
    , "-- - this module is the pure adapter layer (kernel types, transformer-aligned)."
    , "--"
    , "-- Keep both under `_build/`."
    , ""
    ]
      <> agdaKernelPrelude
      <> [ ""
    , "-- FFI boundary uses Agda's builtin lists (host-native), then we convert into"
    , "-- the LogOS kernel list type (transformer-aligned adapter boundary)."
    , "open import Agda.Builtin.List as BL renaming (List to BList; [] to []B; _∷_ to _∷B_)"
    , "open import Agda.Builtin.Maybe as BM using (Maybe; just; nothing)"
    , ""
    , "open import Agda.Builtin.String using (String; primStringAppend)"
    , ""
    , "import " <> hostMod <> " as Host"
    , ""
    , "import LogOS.Ports.Metamath as MM"
    , ""
    ]
      <> agdaFormulaTypeDecl
      <> [ ""
    , "numSymbols : ℕ"
    , "numSymbols = " <> show (ahNumSymbols hdr)
    , ""
    , "numAssertions : ℕ"
    , "numAssertions = " <> show (ahNumAssertions hdr)
    ]
      <> setMMSigBlock syms
      <> [ ""
    , ""
    , "-- Default artifact path (can be overridden at runtime by setting the env var below)."
    , "defaultMMDBPath : String"
    , "defaultMMDBPath = " <> agdaString dbPath
    , ""
    , "mmdbEnvVar : String"
    , "mmdbEnvVar = " <> agdaString (roEnvVar opts)
    , ""
    , "toList : ∀ {ℓ} {A : Set ℓ} → BList A → List A"
    , "toList []B = []"
    , "toList (x ∷B xs) = x ∷ toList xs"
    , ""
    , "toList2 : ∀ {ℓ} {A : Set ℓ} → BList (BList A) → List (List A)"
    , "toList2 []B = []"
    , "toList2 (xs ∷B xss) = toList xs ∷ toList2 xss"
    , ""
    , "-- Adapter layer: expose LogOS-list DB accessors, backed by builtin-list FFI."
    , "hyps : ℕ → List Formula"
    , "hyps n = toList2 (Host.hypsB n)"
    , ""
    , "concl : ℕ → Formula"
    , "concl n = toList (Host.conclB n)"
    , ""
    , "-- Inverse lookup helpers (token/label text -> index)."
    , "symIndex : String → List ℕ"
    , "symIndex s with Host.symIndexB s"
    , "... | nothing = []"
    , "... | just n = n ∷ []"
    , ""
    , "labelIndex : String → List ℕ"
    , "labelIndex s with Host.labelIndexB s"
    , "... | nothing = []"
    , "... | just n = n ∷ []"
    , ""
    , "-- Maybe-flavoured lookups (more convenient for programmatic adapters)."
    , "symIndexM : String → Maybe ℕ"
    , "symIndexM = Host.symIndexB"
    , ""
    , "labelIndexM : String → Maybe ℕ"
    , "labelIndexM = Host.labelIndexB"
    , ""
    , "-- Runtime load status (inspect this before trusting default-valued accessors)."
    , "loadErrorM : Maybe String"
    , "loadErrorM = Host.loadErrorB"
    , ""
    , "hypsByLabelM : String → Maybe (List Formula)"
    , "hypsByLabelM s with labelIndexM s"
    , "... | nothing = nothing"
    , "... | just n = just (hyps n)"
    , ""
    , "conclByLabelM : String → Maybe Formula"
    , "conclByLabelM s with labelIndexM s"
    , "... | nothing = nothing"
    , "... | just n = just (concl n)"
    , ""
    , "-- Direct accessors (index -> original text)."
    , "label : ℕ → String"
    , "label = Host.label"
    , ""
    , "symbol : ℕ → String"
    , "symbol = Host.symbol"
    , ""
    , "-- Pretty-printing helpers (useful for quick inspection in runners)."
    , "infixr 5 _++_"
    , "_++_ : String → String → String"
    , "_++_ = primStringAppend"
    , ""
    , "ppFormula : Formula → String"
    , "ppFormula [] = \"\""
    , "ppFormula (n ∷ []) = symbol n"
    , "ppFormula (n ∷ ns) = symbol n ++ \" \" ++ ppFormula ns"
    , ""
    , "DB : MM.Database Formula"
    , "DB = record { Label = ℕ ; hyps = hyps ; concl = concl }"
    , ""
    , "-- Derived: closure transformer for this database (the whole point)."
    , "module Closed = MM.FromDB DB"
    , ""
    , "-- Symbol table (index -> original token)."
    ]
      <> symbolIndexComments syms
      <> [ "" ]

renderRuntimeHostModule :: String -> ExportAgdaRuntimeOptions -> FilePath -> String
renderRuntimeHostModule hostMod opts dbPath =
  unlines
    (agdaModuleHeader hostMod False
    <> [ ""
    , "-- NOTE: This module is intentionally UNSAFE."
    , "-- It is the explicit GHC FFI boundary for a compiled Metamath artifact (`db.mmdb`)."
    , "-- Keep it under `_build/`."
    , ""
    , "open import Agda.Builtin.List as BL renaming (List to BList)"
    , "open import Agda.Builtin.String using (String)"
    , "open import Agda.Builtin.Maybe as BM using (Maybe)"
    , "open import Agda.Builtin.Nat using (Nat)"
    , ""
    , "-- Runtime-backed database queries (builtin types only at the FFI boundary)."
    , "postulate"
    , "  hypsB  : Nat → BList (BList Nat)"
    , "  conclB : Nat → BList Nat"
    , "  label  : Nat → String"
    , "  symbol : Nat → String"
    , "  symIndexB   : String → Maybe Nat"
    , "  labelIndexB : String → Maybe Nat"
    , "  loadErrorB  : Maybe String"
    , ""
    , "{-# FOREIGN GHC"
    , "import Control.Exception (SomeException, evaluate, try)"
    , "import qualified Data.Array as A"
    , "import Data.Array (Array, (!))"
    , "import Data.Bits"
    , "import qualified Data.ByteString as BS"
    , "import qualified Data.ByteString.Char8 as BS8"
    , "import qualified Data.ByteString.Unsafe as BSU"
    , "import Data.IORef (IORef, newIORef, readIORef, writeIORef)"
    , "import qualified Data.Map.Strict as M"
    , "import qualified Data.Text as T"
    , "import qualified Data.Text.Encoding as TE"
    , "import Data.Word"
    , "import System.Environment (lookupEnv)"
    , "import System.IO.Unsafe (unsafePerformIO)"
    , ""
    , "data MMDB = MMDB"
    , "  { mmdbBytes :: !BS.ByteString"
    , "  , mmdbOffsets :: !(Array Int Int)   -- assertion index -> byte offset"
    , "  , mmdbSymbols :: !(Array Int T.Text) -- symbol index -> token text"
    , "  , mmdbSymbolIndex :: !(M.Map T.Text Int)"
    , "  , mmdbLabelIndex :: !(M.Map T.Text Int)"
    , "  , mmdbNumAssertions :: !Int"
    , "  , mmdbNumSymbols :: !Int"
    , "  }"
    , ""
    , "mmdb_magic :: BS.ByteString"
    , "mmdb_magic = BS8.pack \"MMDB\""
    , ""
    , "mmdb_defaultPath :: FilePath"
    , "mmdb_defaultPath = " <> show dbPath
    , ""
    , "mmdb_envVar :: String"
    , "mmdb_envVar = " <> show (roEnvVar opts)
    , ""
    , "type MMDBResult = Either T.Text MMDB"
    , ""
    , "mmdbSafeIndex :: BS.ByteString -> Int -> Word8"
    , "mmdbSafeIndex bs i ="
    , "  if i < 0 || i >= BS.length bs"
    , "    then error (\"mmdb: truncated at byte index \" <> show i)"
    , "    else BSU.unsafeIndex bs i"
    , ""
    , "getU32le :: BS.ByteString -> Int -> Word32"
    , "getU32le bs i ="
    , "  let b0 = fromIntegral (mmdbSafeIndex bs i) :: Word32"
    , "      b1 = fromIntegral (mmdbSafeIndex bs (i+1)) :: Word32"
    , "      b2 = fromIntegral (mmdbSafeIndex bs (i+2)) :: Word32"
    , "      b3 = fromIntegral (mmdbSafeIndex bs (i+3)) :: Word32"
    , "  in b0 .|. (b1 `shiftL` 8) .|. (b2 `shiftL` 16) .|. (b3 `shiftL` 24)"
    , ""
    , "getU64le :: BS.ByteString -> Int -> Word64"
    , "getU64le bs i ="
    , "  let lo = fromIntegral (getU32le bs i) :: Word64"
    , "      hi = fromIntegral (getU32le bs (i+4)) :: Word64"
    , "  in lo .|. (hi `shiftL` 32)"
    , ""
    , "u32ToIntStrict :: BS.ByteString -> Int -> Int"
    , "u32ToIntStrict bs i ="
    , "  let n = toInteger (getU32le bs i)"
    , "      maxI = toInteger (maxBound :: Int)"
    , "  in if n > maxI"
    , "     then error (\"mmdb: field does not fit Int at byte index \" <> show i <> \": \" <> show n)"
    , "     else fromInteger n"
    , ""
    , "mmdbNeedBytes :: BS.ByteString -> Int -> Integer -> Int"
    , "mmdbNeedBytes bs pos nBytes ="
    , "  let start = toInteger pos"
    , "      end = start + nBytes"
    , "      len = toInteger (BS.length bs)"
    , "      maxI = toInteger (maxBound :: Int)"
    , "  in if pos < 0 || nBytes < 0 || end < start || end > len || end > maxI"
    , "       then error (\"mmdb: truncated/invalid range at byte index \" <> show pos <> \" (need \" <> show nBytes <> \")\")"
    , "       else fromInteger end"
    , ""
    , "safeIndex :: Int -> Integer -> Maybe Int"
    , "safeIndex bound n ="
    , "  let nI = toInteger n"
    , "      b = toInteger bound"
    , "  in if nI < 0 || nI >= b then Nothing else Just (fromInteger nI)"
    , ""
    , "parseHeader :: BS.ByteString -> (Int, Int, Int)"
    , "parseHeader bs ="
    , "  if BS.length bs < 32 then error \"mmdb: truncated header\""
    , "  else"
    , "  let m = BS.take 4 bs"
    , "      ver = getU32le bs 4"
    , "      offSyms ="
    , "        let x = toInteger (getU64le bs 12)"
    , "            maxI = toInteger (maxBound :: Int)"
    , "        in if x > maxI then error \"mmdb: symbol section offset does not fit Int\" else fromInteger x"
    , "      nSyms = u32ToIntStrict bs 20"
    , "      nAsr = u32ToIntStrict bs 24"
    , "  in if m /= mmdb_magic then error \"mmdb: bad magic\""
    , "     else if ver /= 1 then error \"mmdb: unsupported version\""
    , "     else (offSyms, nSyms, nAsr)"
    , ""
    , "parseSymbols :: BS.ByteString -> Int -> Int -> Array Int T.Text"
    , "parseSymbols bs off nSyms ="
    , "  let start = mmdbNeedBytes bs off 4"
    , "      n0 = u32ToIntStrict bs off"
    , "  in if n0 /= nSyms then error \"mmdb: symbol count mismatch\""
    , "     else if nSyms < 0 then error \"mmdb: negative symbol count\""
    , "     else if nSyms == 0 then A.listArray (0, 0) [T.empty]"
    , "     else A.listArray (0, nSyms - 1) (go start nSyms [])"
    , "  where"
    , "    go _ 0 acc = reverse acc"
    , "    go pos k acc ="
    , "      let len = u32ToIntStrict bs pos"
    , "          pos1 = mmdbNeedBytes bs pos 4"
    , "          pos2 = mmdbNeedBytes bs pos1 (toInteger len)"
    , "          tok = BS.take len (BS.drop pos1 bs)"
    , "          txt = TE.decodeUtf8 tok"
    , "      in go pos2 (k - 1) (txt : acc)"
    , ""
    , "skipExpr :: BS.ByteString -> Int -> Int"
    , "skipExpr bs pos ="
    , "  let len = u32ToIntStrict bs pos"
    , "      bytes = 4 + 4 * toInteger len"
    , "  in mmdbNeedBytes bs pos bytes"
    , ""
    , "buildOffsets :: BS.ByteString -> Int -> Int -> [Int] -> [Int]"
    , "buildOffsets bs pos n acc"
    , "  | n < 0 = error \"mmdb: negative assertion count\""
    , "  | n <= 0 = reverse acc"
    , "  | otherwise ="
    , "      let _lblLen = u32ToIntStrict bs pos"
    , "          pos1 = mmdbNeedBytes bs pos 4"
    , "          pos2 = mmdbNeedBytes bs pos1 (toInteger _lblLen)"
    , "          nh = u32ToIntStrict bs pos2"
    , "          pos3 = mmdbNeedBytes bs pos2 4"
    , "          pos4 = skipHyps nh pos3"
    , "      in buildOffsets bs pos4 (n - 1) (pos : acc)"
    , "  where"
    , "    skipHyps 0 p = p"
    , "    skipHyps k p = skipHyps (k - 1) (skipExpr bs p)"
    , ""
    , "readLabelAt :: BS.ByteString -> Int -> T.Text"
    , "readLabelAt bs off ="
    , "  let len = u32ToIntStrict bs off"
    , "      pos = mmdbNeedBytes bs off 4"
    , "      _ = mmdbNeedBytes bs pos (toInteger len)"
    , "      b = BS.take len (BS.drop pos bs)"
    , "  in TE.decodeUtf8 b"
    , ""
    , "buildLabelIndex :: BS.ByteString -> Array Int Int -> Int -> M.Map T.Text Int"
    , "buildLabelIndex bs offsArr nAsr ="
    , "  M.fromList [ (readLabelAt bs (offsArr ! i), i) | i <- [0 .. nAsr - 1] ]"
    , ""
    , "resolveMMDBPath :: IO FilePath"
    , "resolveMMDBPath = do"
    , "  mp <- lookupEnv mmdb_envVar"
    , "  pure (maybe mmdb_defaultPath id mp)"
    , ""
    , "loadMMDBUnsafe :: FilePath -> IO MMDB"
    , "loadMMDBUnsafe path = do"
    , "  bs <- BS.readFile path"
    , "  let (offSyms, nSyms, nAsr) = parseHeader bs"
    , "      syms = parseSymbols bs offSyms nSyms"
    , "      offs = buildOffsets bs 32 nAsr []"
    , "      offsArr = if nAsr <= 0 then A.listArray (0, 0) [0] else A.listArray (0, nAsr - 1) offs"
    , "      symIx = M.fromList [ (syms ! i, i) | i <- [0 .. nSyms - 1] ]"
    , "      lblIx = buildLabelIndex bs offsArr nAsr"
    , "  pure (MMDB bs offsArr syms symIx lblIx nAsr nSyms)"
    , ""
    , "touchMMDB :: MMDB -> ()"
    , "touchMMDB db ="
    , "  let off0 = if mmdbNumAssertions db <= 0 then 0 else mmdbOffsets db ! 0"
    , "      sym0 = if mmdbNumSymbols db <= 0 then T.empty else mmdbSymbols db ! 0"
    , "  in off0 `seq` sym0 `seq` ()"
    , ""
    , "tryLoadMMDB :: FilePath -> IO MMDBResult"
    , "tryLoadMMDB path = do"
    , "  e <- (try $ do"
    , "    db <- loadMMDBUnsafe path"
    , "    evaluate (touchMMDB db)"
    , "    pure db"
    , "    ) :: IO (Either SomeException MMDB)"
    , "  pure (either (Left . T.pack . show) Right e)"
    , ""
    , "{-# NOINLINE mmdb_cache #-}"
    , "mmdb_cache :: IORef (Maybe (FilePath, MMDBResult))"
    , "mmdb_cache = unsafePerformIO (newIORef Nothing)"
    , ""
    , "getMMDBResult :: IO MMDBResult"
    , "getMMDBResult = do"
    , "  path <- resolveMMDBPath"
    , "  cached <- readIORef mmdb_cache"
    , "  case cached of"
    , "    Just (cachedPath, result) | cachedPath == path -> pure result"
    , "    _ -> do"
    , "      result <- tryLoadMMDB path"
    , "      writeIORef mmdb_cache (Just (path, result))"
    , "      pure result"
    , ""
    , "withMMDB :: a -> (MMDB -> a) -> a"
    , "withMMDB def k = unsafePerformIO $ do"
    , "  result <- getMMDBResult"
    , "  pure (either (const def) k result)"
    , ""
    , "{-# NOINLINE mmdb_loadError #-}"
    , "mmdb_loadError :: Maybe T.Text"
    , "mmdb_loadError = unsafePerformIO $ do"
    , "  result <- getMMDBResult"
    , "  pure (either Just (const Nothing) result)"
    , ""
    , "readExprAt :: BS.ByteString -> Int -> ([Integer], Int)"
    , "readExprAt bs pos ="
    , "  let len = u32ToIntStrict bs pos"
    , "      pos1 = mmdbNeedBytes bs pos 4"
    , "      pos2 = mmdbNeedBytes bs pos1 (4 * toInteger len)"
    , "      syms = [ fromIntegral (getU32le bs (pos1 + 4*j)) :: Integer | j <- [0 .. len - 1] ]"
    , "  in (syms, pos2)"
    , ""
    , "readHypsAt :: BS.ByteString -> Int -> ([[Integer]], Int)"
    , "readHypsAt bs pos ="
    , "  let lblLen = u32ToIntStrict bs pos"
    , "      pos1 = mmdbNeedBytes bs pos 4"
    , "      pos2 = mmdbNeedBytes bs pos1 (toInteger lblLen)"
    , "      nh = u32ToIntStrict bs pos2"
    , "      pos3 = mmdbNeedBytes bs pos2 4"
    , "  in go nh pos3 []"
    , "  where"
    , "    go 0 p acc = (reverse acc, p)"
    , "    go k p acc ="
    , "      let (e, p') = readExprAt bs p"
    , "      in go (k - 1) p' (e : acc)"
    , ""
    , "mmdb_hyps :: Integer -> [[Integer]]"
    , "mmdb_hyps n ="
    , "  withMMDB [] $ \\db ->"
    , "    case safeIndex (mmdbNumAssertions db) n of"
    , "      Nothing -> []"
    , "      Just i ->"
    , "        let off = mmdbOffsets db ! i"
    , "            (hs, _) = readHypsAt (mmdbBytes db) off"
    , "        in hs"
    , ""
    , "mmdb_concl :: Integer -> [Integer]"
    , "mmdb_concl n ="
    , "  withMMDB [] $ \\db ->"
    , "    case safeIndex (mmdbNumAssertions db) n of"
    , "      Nothing -> []"
    , "      Just i ->"
    , "        let off = mmdbOffsets db ! i"
    , "            (_hs, p) = readHypsAt (mmdbBytes db) off"
    , "            (c, _) = readExprAt (mmdbBytes db) p"
    , "        in c"
    , ""
    , "mmdb_label :: Integer -> T.Text"
    , "mmdb_label n ="
    , "  withMMDB T.empty $ \\db ->"
    , "    case safeIndex (mmdbNumAssertions db) n of"
    , "      Nothing -> T.empty"
    , "      Just i -> readLabelAt (mmdbBytes db) (mmdbOffsets db ! i)"
    , ""
    , "mmdb_symbol :: Integer -> T.Text"
    , "mmdb_symbol n ="
    , "  withMMDB T.empty $ \\db ->"
    , "    case safeIndex (mmdbNumSymbols db) n of"
    , "      Nothing -> T.empty"
    , "      Just i -> mmdbSymbols db ! i"
    , ""
    , "mmdb_symIndex :: T.Text -> Maybe Integer"
    , "mmdb_symIndex t ="
    , "  withMMDB Nothing $ \\db ->"
    , "    fmap fromIntegral (M.lookup t (mmdbSymbolIndex db))"
    , ""
    , "mmdb_labelIndex :: T.Text -> Maybe Integer"
    , "mmdb_labelIndex t ="
    , "  withMMDB Nothing $ \\db ->"
    , "    fmap fromIntegral (M.lookup t (mmdbLabelIndex db))"
    , ""
    , "mmdb_loadErrorText :: Maybe T.Text"
    , "mmdb_loadErrorText = mmdb_loadError"
    , "#-}"
    , ""
    , "{-# COMPILE GHC hypsB = mmdb_hyps #-}"
    , "{-# COMPILE GHC conclB = mmdb_concl #-}"
    , "{-# COMPILE GHC label = mmdb_label #-}"
    , "{-# COMPILE GHC symbol = mmdb_symbol #-}"
    , "{-# COMPILE GHC symIndexB = mmdb_symIndex #-}"
    , "{-# COMPILE GHC labelIndexB = mmdb_labelIndex #-}"
    , "{-# COMPILE GHC loadErrorB = mmdb_loadErrorText #-}"
    , ""
    ]
    )

renderRunnerModule :: String -> String -> String
renderRunnerModule runnerMod dbMod =
  unlines
    (agdaModuleHeader runnerMod False
    <>
    [ ""
    , "-- Small runner for the runtime-backed Metamath DB."
    , "-- This is intentionally unsafe (explicit GHC FFI for printing)."
    , ""
    , "open import Agda.Builtin.IO using (IO)"
    , "open import Agda.Builtin.Unit using (⊤)"
    , "open import Agda.Builtin.Maybe using (Maybe; just; nothing)"
    , "open import Agda.Builtin.String using (String; primStringAppend; primShowNat)"
    , ""
    , "import " <> dbMod <> " as DB"
    , ""
    , "infixr 5 _++_"
    , "_++_ : String → String → String"
    , "_++_ = primStringAppend"
    , ""
    , "loadStatusFrom : Maybe String → String"
    , "loadStatusFrom nothing = \"ok\""
    , "loadStatusFrom (just err) = \"error: \" ++ err"
    , ""
    , "loadStatus : String"
    , "loadStatus = loadStatusFrom DB.loadErrorM"
    , ""
    , "postulate"
    , "  putStrLn : String → IO ⊤"
    , ""
    , "{-# FOREIGN GHC import qualified Data.Text.IO as TIO #-}"
    , "{-# COMPILE GHC putStrLn = TIO.putStrLn #-}"
    , ""
    , "msg : String"
    , "msg ="
    , "  \"symbols: \" ++ primShowNat DB.numSymbols ++ \", assertions: \" ++ primShowNat DB.numAssertions"
    , "  ++ \"\\n\" ++ \"load: \" ++ loadStatus"
    , "  ++ \"\\n\" ++ \"[0] \" ++ DB.label 0"
    , "  ++ \"\\n\" ++ \"[1] \" ++ DB.label 1"
    , "  ++ \"\\n\" ++ \"sym[0] \" ++ DB.symbol 0"
    , "  ++ \"\\n\" ++ \"concl[0] \" ++ DB.ppFormula (DB.concl 0)"
    , ""
    , "main : IO ⊤"
    , "main = putStrLn msg"
    ])
