{-
LogOS: an Agda research library for foundational logic system architecture.
Copyright (C) 2026 AI.IMPACT GmbH
SPDX-License-Identifier: GPL-3.0-only
-}

{-# OPTIONS --safe #-}
module LogOS.Theorems.Reflection.NucleusMu where

open import LogOS.Prelude hiding (refl; trans) renaming (_⊔_ to _⊔ℓ_)
open import Data.List using (List; []; _∷_)
open import LogOS.Minimal.Con using (ConPoset; MonoOn)
open import LogOS.Minimal.Closure using (ClosureOp)
open import LogOS.Minimal.Truth as Truth

-- Minimal list-wise predicate.
data All {ℓ₁ ℓ₂ : Level} {A : Set ℓ₁}
         (P : A → Set ℓ₂) : List A → Set (ℓ₁ ⊔ℓ ℓ₂) where
  all[] : All P []
  all∷  : ∀ {x xs} → P x → All P xs → All P (x ∷ xs)

All-map
  : ∀ {ℓ₁ ℓ₂ ℓ₃} {A : Set ℓ₁}
    {P : A → Set ℓ₂} {Q : A → Set ℓ₃}
  → (∀ x → P x → Q x)
  → ∀ {xs} → All P xs → All Q xs
All-map f all[] = all[]
All-map f (all∷ px pxs) = all∷ (f _ px) (All-map f pxs)

-- Join-semilattice structure on a preorder.
record JoinSemilattice {ℓ : Level} : Set (lsuc ℓ) where
  field
    CP : ConPoset ℓ

  open ConPoset CP public

  infixl 6 _⊔_

  field
    _⊔_ : Con → Con → Con
    ⊥   : Con
    ⊥-least : ∀ a → _⊑_ ⊥ a
    ⊔-ub₁  : ∀ a b → _⊑_ a (a ⊔ b)
    ⊔-ub₂  : ∀ a b → _⊑_ b (a ⊔ b)
    ⊔-least : ∀ {a b c} → _⊑_ a c → _⊑_ b c → _⊑_ (a ⊔ b) c

-- Avoid opening JoinSemilattice globally: it exports projections like `Con`
-- and `_⊑_`, which leads to ambiguous projection resolution under `-W all
-- -W error`. Use qualified names or open a specific `J` locally instead.

⊔-mono
  : ∀ {ℓ} {J : JoinSemilattice {ℓ}} {a b c d : JoinSemilattice.Con J}
  → ConPoset._⊑_ (JoinSemilattice.CP J) a c
  → ConPoset._⊑_ (JoinSemilattice.CP J) b d
  → ConPoset._⊑_ (JoinSemilattice.CP J)
      (JoinSemilattice._⊔_ J a b)
      (JoinSemilattice._⊔_ J c d)
⊔-mono {J = J} {c = c} {d = d} a≤c b≤d =
  let
    CP = JoinSemilattice.CP J
    step₁ = ConPoset.trans CP a≤c (JoinSemilattice.⊔-ub₁ J c d)
    step₂ = ConPoset.trans CP b≤d (JoinSemilattice.⊔-ub₂ J c d)
  in JoinSemilattice.⊔-least J step₁ step₂

-- Closure components: monotone inflationary endomaps.
record Component {ℓ : Level} (J : JoinSemilattice {ℓ}) : Set (lsuc ℓ) where
  open JoinSemilattice J
  field
    op   : Con → Con
    mono : MonoOn CP op
    infl : ∀ c → _⊑_ c (op c)

open Component public

-- Pointwise preorder on endomaps.
infix 4 _≤ᵉ_
_≤ᵉ_
  : ∀ {ℓ} {J : JoinSemilattice {ℓ}}
  → (JoinSemilattice.Con J → JoinSemilattice.Con J)
  → (JoinSemilattice.Con J → JoinSemilattice.Con J)
  → Set ℓ
_≤ᵉ_ {J = J} F G = ∀ c → ConPoset._⊑_ (JoinSemilattice.CP J) (F c) (G c)

-- Pointwise join of a list of components.
joinComponents
  : ∀ {ℓ} {J : JoinSemilattice {ℓ}}
  → List (Component J) → JoinSemilattice.Con J → JoinSemilattice.Con J
joinComponents {J = J} [] _ = JoinSemilattice.⊥ J
joinComponents {J = J} (C ∷ Cs) c =
  let open JoinSemilattice J in
  op C c ⊔ joinComponents {J = J} Cs c

joinComponents-mono
  : ∀ {ℓ} {J : JoinSemilattice {ℓ}}
  → (Cs : List (Component J))
  → MonoOn (JoinSemilattice.CP J) (joinComponents {J = J} Cs)
joinComponents-mono {J = J} [] {c} {d} _ =
  ConPoset.refl (JoinSemilattice.CP J)
joinComponents-mono {J = J} (C ∷ Cs) {c} {d} c≤d =
  ⊔-mono {J = J}
    (Component.mono C c≤d)
    (joinComponents-mono {J = J} Cs c≤d)

joinComponents-ub
  : ∀ {ℓ} {J : JoinSemilattice {ℓ}}
    (Cs : List (Component J))
  → All (λ C → _≤ᵉ_ {J = J} (op C) (joinComponents {J = J} Cs)) Cs
joinComponents-ub {J = J} [] = all[]
joinComponents-ub {J = J} (C ∷ Cs) =
  all∷
      (λ c → JoinSemilattice.⊔-ub₁ J (op C c) (joinComponents {J = J} Cs c))
      (All-map
        (λ _ le c →
          ConPoset.trans (JoinSemilattice.CP J) (le c)
            (JoinSemilattice.⊔-ub₂ J (op C c) (joinComponents {J = J} Cs c)))
        (joinComponents-ub {J = J} Cs))

joinComponents-least
  : ∀ {ℓ} {J : JoinSemilattice {ℓ}}
    (Cs : List (Component J))
    {F : JoinSemilattice.Con J → JoinSemilattice.Con J}
  → All (λ C → _≤ᵉ_ {J = J} (op C) F) Cs
  → _≤ᵉ_ {J = J} (joinComponents {J = J} Cs) F
joinComponents-least {J = J} [] {F = F} allF c = JoinSemilattice.⊥-least J (F c)
joinComponents-least {J = J} (C ∷ Cs) {F = F} (all∷ head tail) c =
  JoinSemilattice.⊔-least J (head c) (joinComponents-least {J = J} Cs {F = F} tail c)

-- Least fixed point closure generated by components (via μ).
module Generated
  {ℓ : Level}
  (J : JoinSemilattice {ℓ})
  (ωCPO : Truth.GuardedCore.OmegaCPO (JoinSemilattice.CP J))
  (Cs : List (Component J))
  where

  open JoinSemilattice J
  open Truth.GuardedCore.Kleene {CP = CP} ωCPO

  step : Con → Con → Con
  step base c = base ⊔ (c ⊔ joinComponents {J = J} Cs c)

  step-mono : ∀ base → MonoOn CP (step base)
  step-mono base {c} {d} c≤d =
    ⊔-mono {J = J}
      (ConPoset.refl CP)
      (⊔-mono {J = J} c≤d (joinComponents-mono {J = J} Cs c≤d))

  step-infl : ∀ base c → _⊑_ c (step base c)
  step-infl base c =
    ConPoset.trans CP
      (⊔-ub₁ c (joinComponents {J = J} Cs c))
      (⊔-ub₂ base (c ⊔ joinComponents {J = J} Cs c))

  generated : Con → Con
  generated base = μ (step base)

  generated-unfold-left
    : ∀ base → _⊑_ (generated base) (step base (generated base))
  generated-unfold-left base =
    μ-unfold-left (step base) (step-mono base)

  generated-least
    : ∀ base c
      → _⊑_ (step base c) c
      → _⊑_ (generated base) c
  generated-least base c pre =
    μ-induction (step base) (step-mono base) c pre

  generated-unfold-right
    : ∀ base
      → ScottContinuous (step base)
      → _⊑_ (step base (generated base)) (generated base)
  generated-unfold-right base SC =
    μ-unfold-right-infl (step base) SC (step-infl base)

  -- Monotonicity in the seed/base.

  step-mono-base
    : ∀ {base base'} → _⊑_ base base' → ∀ c → _⊑_ (step base c) (step base' c)
  step-mono-base {base} {base'} base≤base' c =
    ⊔-mono {J = J}
      base≤base'
      (ConPoset.refl CP {c = c ⊔ joinComponents {J = J} Cs c})

  generated-mono
    : ∀ {base base'} → _⊑_ base base' → _⊑_ (generated base) (generated base')
  generated-mono {base} {base'} base≤base' =
    Truth.GuardedCore.OmegaCPO.least ωCPO
      (iter (step base))
      (generated base')
      (λ n →
        ConPoset.trans CP
          (iter-mono n)
          (Truth.GuardedCore.OmegaCPO.ub ωCPO (iter (step base')) n))
    where
      iter-mono : ∀ n → _⊑_ (iter (step base) n) (iter (step base') n)
      iter-mono zero = ConPoset.refl CP
      iter-mono (suc n) =
        ConPoset.trans CP
          (step-mono-base base≤base' (iter (step base) n))
          (step-mono base' (iter-mono n))

  -- Closure operator generated by the components, as an endomap on `Con`.
  --
  -- This is the “nucleus generated by a base seed” view: `cl base` is the least
  -- fixed point containing `base` and closed under `Cs`. Idempotence is proved
  -- using a continuity witness for `step base` (Kleene μ-unfold-right).

  generatedClosureOp
    : (SC : ∀ base → ScottContinuous (step base))
    → ClosureOp CP
  generatedClosureOp SC =
    record
      { cl        = generated
      ; mono      = generated-mono
      ; infl      = generated-infl
      ; idemp-lax = idemp
      }
    where
      generated-infl : ∀ base → _⊑_ base (generated base)
      generated-infl base =
        let ω⊥ = Truth.GuardedCore.OmegaCPO.⊥ ωCPO in
        ConPoset.trans CP
          (⊔-ub₁ base (ω⊥ ⊔ joinComponents {J = J} Cs ω⊥))
          (Truth.GuardedCore.OmegaCPO.ub ωCPO (iter (step base)) (suc zero))

      joinComponents≤
        : ∀ base → _⊑_ (joinComponents {J = J} Cs (generated base)) (generated base)
      joinComponents≤ base =
        let
          rest≤step : _⊑_ (generated base ⊔ joinComponents {J = J} Cs (generated base))
                         (step base (generated base))
          rest≤step =
            ⊔-ub₂ base (generated base ⊔ joinComponents {J = J} Cs (generated base))
        in
        ConPoset.trans CP
          (⊔-ub₂ (generated base) (joinComponents {J = J} Cs (generated base)))
          (ConPoset.trans CP rest≤step (generated-unfold-right base (SC base)))

      idemp : ∀ base → _⊑_ (generated (generated base)) (generated base)
      idemp base =
        generated-least
          (generated base)
          (generated base)
          step≤
        where
          step≤ : _⊑_ (step (generated base) (generated base)) (generated base)
          step≤ =
            ⊔-least
              (ConPoset.refl CP)
              (⊔-least
                (ConPoset.refl CP)
                (joinComponents≤ base))
