{-
LogOS: models for AI-driven, human-on-the-loop, machine-checked formal reasoning
Copyright (C) 2026 AI.IMPACT GmbH
SPDX-License-Identifier: GPL-3.0-only
-}

{-# OPTIONS --safe #-}
module LogOS.Theorems.Reflection.NucleusMu where

open import LogOS.Prelude hiding (refl; trans; _⊔_)
open import LogOS.Prelude.List using (List; []; _∷_; All; all[]; all∷; All-map) renaming (map to mapList)
open import LogOS.Minimal.Con using (ConPreorder; MonoOn)
open import LogOS.Minimal.Closure using (ClosureOp)
open import LogOS.Minimal.Truth as Truth
import LogOS.Theorems.Boundary.MuFusion as MuFusion

-- Join-semilattice structure on a preorder.
record JoinSemilattice {ℓ : Level} : Set (lsuc ℓ) where
  field
    CP : ConPreorder ℓ

  open ConPreorder CP public

  infixl 6 _⊔_

  field
    _⊔_ : Con → Con → Con
    ⊥   : Con
    ⊥-least : ∀ a → _⊑_ ⊥ a
    ⊔-ub₁  : ∀ a b → _⊑_ a (a ⊔ b)
    ⊔-ub₂  : ∀ a b → _⊑_ b (a ⊔ b)
    ⊔-least : ∀ {a b c} → _⊑_ a c → _⊑_ b c → _⊑_ (a ⊔ b) c

-- Avoid opening JoinSemilattice globally: it exports projections like `Con`
-- and `_⊑_`, which leads to ambiguous projection resolution under `-W all
-- -W error`. Use qualified names or open a specific `J` locally instead.

-- Coherence between two “bottoms” that may otherwise be introduced
-- independently:
--
-- - `JoinSemilattice.⊥` is the join-semilattice bottom used by `joinComponents`.
-- - `OmegaCPO.⊥` is the ωCPO bottom used by Kleene iteration.
--
-- Without this (optional) coherence, some transport/naturality statements need
-- extra “map ⊥ ≤ ⊥” assumptions even when the map is already strict w.r.t. the
-- ωCPO structure.
record BottomCoherence {ℓ : Level}
  (J : JoinSemilattice {ℓ})
  (ωCPO : Truth.GuardedCore.OmegaCPO (JoinSemilattice.CP J))
  : Set (lsuc ℓ) where
  private
    CP : ConPreorder ℓ
    CP = JoinSemilattice.CP J

  open ConPreorder CP
  open Truth.GuardedCore.OmegaCPO ωCPO renaming (⊥ to ω⊥)

  field
    ω⊥≤⊥ : _⊑_ ω⊥ (JoinSemilattice.⊥ J)

  ⊥≤ω⊥ : _⊑_ (JoinSemilattice.⊥ J) ω⊥
  ⊥≤ω⊥ = JoinSemilattice.⊥-least J ω⊥

⊔-mono
  : ∀ {ℓ} {J : JoinSemilattice {ℓ}} {a b c d : JoinSemilattice.Con J}
  → ConPreorder._⊑_ (JoinSemilattice.CP J) a c
  → ConPreorder._⊑_ (JoinSemilattice.CP J) b d
  → ConPreorder._⊑_ (JoinSemilattice.CP J)
      (JoinSemilattice._⊔_ J a b)
      (JoinSemilattice._⊔_ J c d)
⊔-mono {J = J} {c = c} {d = d} a≤c b≤d =
  let
    CP = JoinSemilattice.CP J
    step₁ = ConPreorder.trans CP a≤c (JoinSemilattice.⊔-ub₁ J c d)
    step₂ = ConPreorder.trans CP b≤d (JoinSemilattice.⊔-ub₂ J c d)
  in JoinSemilattice.⊔-least J step₁ step₂

-- Closure components: monotone inflationary endomaps.
record Component {ℓ : Level} (J : JoinSemilattice {ℓ}) : Set (lsuc ℓ) where
  open JoinSemilattice J
  field
    op   : Con → Con
    mono : MonoOn CP op
    infl : ∀ c → _⊑_ c (op c)

open Component public

-- Pointwise preorder on endomaps.
infix 4 _≤ᵉ_
_≤ᵉ_
  : ∀ {ℓ} {J : JoinSemilattice {ℓ}}
  → (JoinSemilattice.Con J → JoinSemilattice.Con J)
  → (JoinSemilattice.Con J → JoinSemilattice.Con J)
  → Set ℓ
_≤ᵉ_ {J = J} F G = ∀ c → ConPreorder._⊑_ (JoinSemilattice.CP J) (F c) (G c)

-- Pointwise join of a list of components.
joinComponents
  : ∀ {ℓ} {J : JoinSemilattice {ℓ}}
  → List (Component J) → JoinSemilattice.Con J → JoinSemilattice.Con J
joinComponents {J = J} [] _ = JoinSemilattice.⊥ J
joinComponents {J = J} (C ∷ Cs) c =
  let open JoinSemilattice J in
  op C c ⊔ joinComponents {J = J} Cs c

joinComponents-mono
  : ∀ {ℓ} {J : JoinSemilattice {ℓ}}
  → (Cs : List (Component J))
  → MonoOn (JoinSemilattice.CP J) (joinComponents {J = J} Cs)
joinComponents-mono {J = J} [] {c} {d} _ =
  ConPreorder.refl (JoinSemilattice.CP J)
joinComponents-mono {J = J} (C ∷ Cs) {c} {d} c≤d =
  ⊔-mono {J = J}
    (Component.mono C c≤d)
    (joinComponents-mono {J = J} Cs c≤d)

joinComponents-ub
  : ∀ {ℓ} {J : JoinSemilattice {ℓ}}
    (Cs : List (Component J))
  → All (λ C → _≤ᵉ_ {J = J} (op C) (joinComponents {J = J} Cs)) Cs
joinComponents-ub {J = J} [] = all[]
joinComponents-ub {J = J} (C ∷ Cs) =
  all∷
      (λ c → JoinSemilattice.⊔-ub₁ J (op C c) (joinComponents {J = J} Cs c))
      (All-map
        (λ _ le c →
          ConPreorder.trans (JoinSemilattice.CP J) (le c)
            (JoinSemilattice.⊔-ub₂ J (op C c) (joinComponents {J = J} Cs c)))
        (joinComponents-ub {J = J} Cs))

joinComponents-least
  : ∀ {ℓ} {J : JoinSemilattice {ℓ}}
    (Cs : List (Component J))
    {F : JoinSemilattice.Con J → JoinSemilattice.Con J}
  → All (λ C → _≤ᵉ_ {J = J} (op C) F) Cs
  → _≤ᵉ_ {J = J} (joinComponents {J = J} Cs) F
joinComponents-least {J = J} [] {F = F} allF c = JoinSemilattice.⊥-least J (F c)
joinComponents-least {J = J} (C ∷ Cs) {F = F} (all∷ head tail) c =
  JoinSemilattice.⊔-least J (head c) (joinComponents-least {J = J} Cs {F = F} tail c)

-- Least fixed point closure generated by components (via μ).
module Generated
  {ℓ : Level}
  (J : JoinSemilattice {ℓ})
  (ωCPO : Truth.GuardedCore.OmegaCPO (JoinSemilattice.CP J))
  (Cs : List (Component J))
  where

  open JoinSemilattice J
  open Truth.GuardedCore.Kleene {CP = CP} ωCPO

  step : Con → Con → Con
  step base c = base ⊔ (c ⊔ joinComponents {J = J} Cs c)

  step-mono : ∀ base → MonoOn CP (step base)
  step-mono base {c} {d} c≤d =
    ⊔-mono {J = J}
      (ConPreorder.refl CP)
      (⊔-mono {J = J} c≤d (joinComponents-mono {J = J} Cs c≤d))

  step-infl : ∀ base c → _⊑_ c (step base c)
  step-infl base c =
    ConPreorder.trans CP
      (⊔-ub₁ c (joinComponents {J = J} Cs c))
      (⊔-ub₂ base (c ⊔ joinComponents {J = J} Cs c))

  generated : Con → Con
  generated base = μ (step base)

  generated-unfold-left
    : ∀ base → _⊑_ (generated base) (step base (generated base))
  generated-unfold-left base =
    μ-unfold-left (step base) (step-mono base)

  generated-least
    : ∀ base c
      → _⊑_ (step base c) c
      → _⊑_ (generated base) c
  generated-least base c pre =
    μ-induction (step base) (step-mono base) c pre

  generated-unfold-right
    : ∀ base
      → ScottContinuous (step base)
      → _⊑_ (step base (generated base)) (generated base)
  generated-unfold-right base SC =
    μ-unfold-right-infl (step base) SC (step-infl base)

  -- Monotonicity in the seed/base.

  step-mono-base
    : ∀ {base base'} → _⊑_ base base' → ∀ c → _⊑_ (step base c) (step base' c)
  step-mono-base {base} {base'} base≤base' c =
    ⊔-mono {J = J}
      base≤base'
      (ConPreorder.refl CP {c = c ⊔ joinComponents {J = J} Cs c})

  generated-mono
    : ∀ {base base'} → _⊑_ base base' → _⊑_ (generated base) (generated base')
  generated-mono {base} {base'} base≤base' =
    μ-mono (step-mono base') (step-mono-base base≤base')

  -- Closure operator generated by the components, as an endomap on `Con`.
  --
  -- This is the “nucleus generated by a base seed” view: `cl base` is the least
  -- fixed point containing `base` and closed under `Cs`. Idempotence is proved
  -- using a continuity witness for `step base` (Kleene μ-unfold-right).

  generatedClosureOp
    : (SC : ∀ base → ScottContinuous (step base))
    → ClosureOp CP
  generatedClosureOp SC =
    record
      { cl        = generated
      ; mono      = generated-mono
      ; infl      = generated-infl
      ; idemp-lax = idemp
      }
    where
      generated-infl : ∀ base → _⊑_ base (generated base)
      generated-infl base =
        let ω⊥ = Truth.GuardedCore.OmegaCPO.⊥ ωCPO in
        ConPreorder.trans CP
          (⊔-ub₁ base (ω⊥ ⊔ joinComponents {J = J} Cs ω⊥))
          (Truth.GuardedCore.OmegaCPO.ub ωCPO (iter (step base)) (suc zero))

      joinComponents≤
        : ∀ base → _⊑_ (joinComponents {J = J} Cs (generated base)) (generated base)
      joinComponents≤ base =
        let
          rest≤step : _⊑_ (generated base ⊔ joinComponents {J = J} Cs (generated base))
                         (step base (generated base))
          rest≤step =
            ⊔-ub₂ base (generated base ⊔ joinComponents {J = J} Cs (generated base))
        in
        ConPreorder.trans CP
          (⊔-ub₂ (generated base) (joinComponents {J = J} Cs (generated base)))
          (ConPreorder.trans CP rest≤step (generated-unfold-right base (SC base)))

      idemp : ∀ base → _⊑_ (generated (generated base)) (generated base)
      idemp base =
        generated-least
          (generated base)
          (generated base)
          step≤
        where
          step≤ : _⊑_ (step (generated base) (generated base)) (generated base)
          step≤ =
            ⊔-least
              (ConPreorder.refl CP)
              (⊔-least
                (ConPreorder.refl CP)
                (joinComponents≤ base))

-- --------------------------------------------------------------------------
-- Naturality / simulation: ω-continuous maps transport the generated closure.
--
-- This is the canonical “abstract interpretation” principle for `generated`:
-- if `map` preserves ⊥ and binary joins (laxly), is ω-continuous (for chains),
-- and commutes (laxly) with each component op, then it transports the Kleene μ
-- of `step` as an inequality.
--
-- The proof is a single use of `μ-fusion≤` once the step-level commutation is
-- packaged.
-- --------------------------------------------------------------------------

module Naturality
  {ℓ₁ ℓ₂ : Level}
  (J₁ : JoinSemilattice {ℓ₁})
  (J₂ : JoinSemilattice {ℓ₂})
  (ω₁ : Truth.GuardedCore.OmegaCPO (JoinSemilattice.CP J₁))
  (ω₂ : Truth.GuardedCore.OmegaCPO (JoinSemilattice.CP J₂))
  (Cs : List (Component J₁))
  (mapC : Component J₁ → Component J₂)
  where

  private
    CP₁ : ConPreorder ℓ₁
    CP₁ = JoinSemilattice.CP J₁

    CP₂ : ConPreorder ℓ₂
    CP₂ = JoinSemilattice.CP J₂

    module MF = MuFusion.For CP₁ CP₂

    module JS₁ = JoinSemilattice J₁
    module JS₂ = JoinSemilattice J₂

    Cs₂ : List (Component J₂)
    Cs₂ = mapList mapC Cs

    module G₁ = Generated J₁ ω₁ Cs
    module G₂ = Generated J₂ ω₂ Cs₂

    trans₂ : ∀ {x y z} → JS₂._⊑_ x y → JS₂._⊑_ y z → JS₂._⊑_ x z
    trans₂ = ConPreorder.trans CP₂

    refl₂ : ∀ {x} → JS₂._⊑_ x x
    refl₂ = ConPreorder.refl CP₂

  module _
    {map : JS₁.Con → JS₂.Con}
    (M : MF.OmegaCPOMap ω₁ ω₂ map)
    (map⊔≤ : ∀ a b → JS₂._⊑_ (map (a JS₁.⊔ b)) (map a JS₂.⊔ map b))
    (comm-op : ∀ (C : Component J₁) c → JS₂._⊑_ (map (op C c)) (op (mapC C) (map c)))
    (bot₁ : BottomCoherence J₁ ω₁)
    (bot₂ : BottomCoherence J₂ ω₂)
    where

    private
      map⊥≤ : JS₂._⊑_ (map JS₁.⊥) JS₂.⊥
      map⊥≤ =
        let
          open MF.OmegaCPOMap M
          open Truth.GuardedCore.OmegaCPO ω₁ renaming (⊥ to ω⊥₁)
          ⊥≤ω⊥₁ : JS₁._⊑_ JS₁.⊥ ω⊥₁
          ⊥≤ω⊥₁ = BottomCoherence.⊥≤ω⊥ bot₁

          ω⊥₂≤⊥₂ : JS₂._⊑_ (map ω⊥₁) JS₂.⊥
          ω⊥₂≤⊥₂ =
            trans₂ strict⊥ (BottomCoherence.ω⊥≤⊥ bot₂)
        in
        trans₂
          (mono-map (⊥≤ω⊥₁))
          ω⊥₂≤⊥₂

      joinComponents-map≤
        : ∀ (Ds : List (Component J₁)) c
        → JS₂._⊑_
            (map (joinComponents {J = J₁} Ds c))
            (joinComponents {J = J₂} (mapList mapC Ds) (map c))
      joinComponents-map≤ [] c = map⊥≤
      joinComponents-map≤ (C ∷ Ds) c =
        trans₂
          (map⊔≤ (op C c) (joinComponents {J = J₁} Ds c))
          (⊔-mono {J = J₂}
            (comm-op C c)
            (joinComponents-map≤ Ds c))

      step-map≤
        : ∀ base c
        → JS₂._⊑_
            (map (G₁.step base c))
            (G₂.step (map base) (map c))
      step-map≤ base c =
        let
          -- First split the outer join.
          outer : JS₂._⊑_
                    (map (base JS₁.⊔ (c JS₁.⊔ joinComponents {J = J₁} Cs c)))
                    (map base JS₂.⊔ map (c JS₁.⊔ joinComponents {J = J₁} Cs c))
          outer = map⊔≤ base (c JS₁.⊔ joinComponents {J = J₁} Cs c)

          -- Then split the inner join and transport the component join.
          inner₁ : JS₂._⊑_
                     (map (c JS₁.⊔ joinComponents {J = J₁} Cs c))
                     (map c JS₂.⊔ map (joinComponents {J = J₁} Cs c))
          inner₁ = map⊔≤ c (joinComponents {J = J₁} Cs c)

          inner₂ : JS₂._⊑_
                     (map c JS₂.⊔ map (joinComponents {J = J₁} Cs c))
                     (map c JS₂.⊔ joinComponents {J = J₂} Cs₂ (map c))
          inner₂ =
            ⊔-mono {J = J₂}
              refl₂
              (joinComponents-map≤ Cs c)

          inner : JS₂._⊑_
                    (map (c JS₁.⊔ joinComponents {J = J₁} Cs c))
                    (map c JS₂.⊔ joinComponents {J = J₂} Cs₂ (map c))
          inner = trans₂ inner₁ inner₂

          all : JS₂._⊑_
                  (map base JS₂.⊔ map (c JS₁.⊔ joinComponents {J = J₁} Cs c))
                  (map base JS₂.⊔ (map c JS₂.⊔ joinComponents {J = J₂} Cs₂ (map c)))
          all = ⊔-mono {J = J₂} refl₂ inner
        in
        trans₂ outer all

    generated-map≤
      : ∀ base
      → JS₂._⊑_
          (map (G₁.generated base))
          (G₂.generated (map base))
    generated-map≤ base =
      MF.μ-fusion≤
        M
        (G₁.step base)
        (G₂.step (map base))
        (G₂.step-mono (map base))
        (G₁.step-infl base)
        (step-map≤ base)
