{-
LogOS: a prototype Agda library for modular dynamic logic systems synthesized by AI
Copyright (C) 2026 AI.IMPACT GmbH
SPDX-License-Identifier: GPL-3.0-only
-}

{-# OPTIONS --safe #-}
module LogOS.Minimal.ConstraintsOverSig where

-- ============================================================================
-- SIGNATURE-INDEXED FREE CONSTRAINT LANGUAGE (SENTENCES / PROGRAMS)
--
-- This is the “missing” nontrivial functorial layer over signatures:
--
-- - For each `Sig`, we build a free constraint algebra generated by the
--   kernel’s monoidal/bulk-boundary operations *plus* atomic boundary generators
--   indexed by `Sig.Iface`.
--
-- - For each signature morphism `σ : SigHom Sig₁ Sig₂`, we get a canonical
--   *covariant* renaming/translation on syntax (the institution `Sen` direction).
--
-- This module is intentionally independent of the kernel: it provides a
-- functorial *language* that can later be interpreted into a particular kernel’s
-- boundary constraints via a valuation of the atoms.
-- ============================================================================

open import LogOS.Prelude
open import LogOS.Prelude using (_×_; _,_)

open import LogOS.Base.Signature using (LogOSSignature; module LogOSSignature)
open import LogOS.Base.Signature.Hom
open import LogOS.Minimal.Con
open import LogOS.Minimal.Adjunction
open import LogOS.Minimal.ConAlg
open import LogOS.Minimal.ConstraintsIndexed as Core

private
  module C {ℓ : Level} =
    Core.With (LogOSSignature ℓ) (λ Sig → LogOSSignature.Iface Sig)

open C public
  hiding (interp∂; interpb; interp∂-mono; interpb-mono)

-- Specialised interpretation/monotonicity (avoid exposing the explicit index argument).

mutual
  interp∂
    : ∀ {ℓ} {Sig : LogOSSignature ℓ} {ℓA : Level}
      (A : ConAlg {ℓA})
      (val : LogOSSignature.Iface Sig → ConAlg.Con_bnd A)
    → Con∂ Sig → ConAlg.Con_bnd A
  interp∂ {Sig = Sig} A val = C.interp∂ Sig A val

  interpb
    : ∀ {ℓ} {Sig : LogOSSignature ℓ} {ℓA : Level}
      (A : ConAlg {ℓA})
      (val : LogOSSignature.Iface Sig → ConAlg.Con_bnd A)
    → Conb Sig → ConAlg.Con_bulk A
  interpb {Sig = Sig} A val = C.interpb Sig A val

mutual
  interp∂-mono
    : ∀ {ℓ} {Sig : LogOSSignature ℓ} {ℓA : Level}
      (A : ConAlg {ℓA})
      (val : LogOSSignature.Iface Sig → ConAlg.Con_bnd A)
      {x y : Con∂ Sig}
    → x ≤∂ y
    → ConAlg._⊑bnd_ A (interp∂ A val x) (interp∂ A val y)
  interp∂-mono {Sig = Sig} A val = C.interp∂-mono Sig A val

  interpb-mono
    : ∀ {ℓ} {Sig : LogOSSignature ℓ} {ℓA : Level}
      (A : ConAlg {ℓA})
      (val : LogOSSignature.Iface Sig → ConAlg.Con_bnd A)
      {x y : Conb Sig}
    → x ≤b y
    → ConAlg._⊑bulk_ A (interpb A val x) (interpb A val y)
  interpb-mono {Sig = Sig} A val = C.interpb-mono Sig A val

-- Covariant renaming/translation along signature morphisms.

renameVal
  : ∀ {ℓ} {Sig₁ Sig₂ : LogOSSignature ℓ}
    (σ : SigHom Sig₁ Sig₂)
  → ∀ {ℓA : Level}
    (A : ConAlg {ℓA})
  → (LogOSSignature.Iface Sig₂ → ConAlg.Con_bnd A)
  → (LogOSSignature.Iface Sig₁ → ConAlg.Con_bnd A)
renameVal σ A val₂ a = val₂ (SigHom.mapIface σ a)

mutual
  rename∂
    : ∀ {ℓ} {Sig₁ Sig₂ : LogOSSignature ℓ}
      (σ : SigHom Sig₁ Sig₂)
    → Con∂ Sig₁ → Con∂ Sig₂
  rename∂ σ I∂ = I∂
  rename∂ σ (x ⊗∂ y) = rename∂ σ x ⊗∂ rename∂ σ y
  rename∂ σ (bnd d) = bnd (renameb σ d)
  rename∂ σ (atom∂ a) = atom∂ (SigHom.mapIface σ a)

  renameb
    : ∀ {ℓ} {Sig₁ Sig₂ : LogOSSignature ℓ}
      (σ : SigHom Sig₁ Sig₂)
    → Conb Sig₁ → Conb Sig₂
  renameb σ Ib = Ib
  renameb σ (x ⊗b y) = renameb σ x ⊗b renameb σ y
  renameb σ (ext c) = ext (rename∂ σ c)

-- Interpretation is natural with respect to renaming:
-- interpreting a translated program under `val₂` is the same as interpreting the
-- original program under the reindexed valuation `val₂ ∘ mapIface σ`.

mutual
  interp∂-rename
    : ∀ {ℓ} {Sig₁ Sig₂ : LogOSSignature ℓ}
      (σ : SigHom Sig₁ Sig₂)
      {ℓA}
      (A : ConAlg {ℓA})
      (val₂ : LogOSSignature.Iface Sig₂ → ConAlg.Con_bnd A)
      (c : Con∂ Sig₁)
    → interp∂ A val₂ (rename∂ σ c) ≡ interp∂ A (renameVal σ A val₂) c
  interp∂-rename σ A val₂ I∂ = refl
  interp∂-rename σ A val₂ (x ⊗∂ y) =
    cong₂ (ConAlg._⊗∂_ A) (interp∂-rename σ A val₂ x) (interp∂-rename σ A val₂ y)
  interp∂-rename σ A val₂ (bnd d) =
    cong (LaxMonoidalAdjunction.bnd (ConAlg.Holo A)) (interpb-rename σ A val₂ d)
  interp∂-rename σ A val₂ (atom∂ a) = refl

  interpb-rename
    : ∀ {ℓ} {Sig₁ Sig₂ : LogOSSignature ℓ}
      (σ : SigHom Sig₁ Sig₂)
      {ℓA}
      (A : ConAlg {ℓA})
      (val₂ : LogOSSignature.Iface Sig₂ → ConAlg.Con_bnd A)
      (d : Conb Sig₁)
    → interpb A val₂ (renameb σ d) ≡ interpb A (renameVal σ A val₂) d
  interpb-rename σ A val₂ Ib = refl
  interpb-rename σ A val₂ (x ⊗b y) =
    cong₂ (ConAlg._⊗b_ A) (interpb-rename σ A val₂ x) (interpb-rename σ A val₂ y)
  interpb-rename σ A val₂ (ext c) =
    cong (ConAlg.ext A) (interp∂-rename σ A val₂ c)

mutual
  rename∂-mono
    : ∀ {ℓ} {Sig₁ Sig₂ : LogOSSignature ℓ}
      (σ : SigHom Sig₁ Sig₂)
      {x y : Con∂ Sig₁}
    → x ≤∂ y
    → rename∂ σ x ≤∂ rename∂ σ y
  rename∂-mono σ refl∂ = refl∂
  rename∂-mono σ (trans∂ p q) = trans∂ (rename∂-mono σ p) (rename∂-mono σ q)
  rename∂-mono σ (cong⊗∂ px py) = cong⊗∂ (rename∂-mono σ px) (rename∂-mono σ py)
  rename∂-mono σ unitbnd = unitbnd
  rename∂-mono σ bnd-⊗ = bnd-⊗
  rename∂-mono σ bnd-I = bnd-I

  renameb-mono
    : ∀ {ℓ} {Sig₁ Sig₂ : LogOSSignature ℓ}
      (σ : SigHom Sig₁ Sig₂)
      {x y : Conb Sig₁}
    → x ≤b y
    → renameb σ x ≤b renameb σ y
  renameb-mono σ reflb = reflb
  renameb-mono σ (transb p q) = transb (renameb-mono σ p) (renameb-mono σ q)
  renameb-mono σ (cong⊗b px py) = cong⊗b (renameb-mono σ px) (renameb-mono σ py)
  renameb-mono σ counit = counit
  renameb-mono σ ext-⊗ = ext-⊗
  renameb-mono σ ext-I = ext-I

renameConAlgHom≡
  : ∀ {ℓ} {Sig₁ Sig₂ : LogOSSignature ℓ}
    (σ : SigHom Sig₁ Sig₂)
  → ConAlgHom≡ (FreeConAlg Sig₁) (FreeConAlg Sig₂)
renameConAlgHom≡ σ =
  record
    { map∂ = rename∂ σ
    ; mapb = renameb σ
    ; unit∂ = refl
    ; unitb = refl
    ; ten∂  = λ _ _ → refl
    ; tenb  = λ _ _ → refl
    ; ext-comm = λ _ → refl
    ; bnd-comm = λ _ → refl
    }

-- Functoriality of renaming (on-the-nose for this syntax).

mutual
  rename∂-id
    : ∀ {ℓ} {Sig : LogOSSignature ℓ}
      (c : Con∂ Sig)
    → rename∂ (idSigHom Sig) c ≡ c
  rename∂-id I∂ = refl
  rename∂-id (x ⊗∂ y) = cong₂ _⊗∂_ (rename∂-id x) (rename∂-id y)
  rename∂-id (bnd d) = cong bnd (renameb-id d)
  rename∂-id (atom∂ _) = refl

  renameb-id
    : ∀ {ℓ} {Sig : LogOSSignature ℓ}
      (d : Conb Sig)
    → renameb (idSigHom Sig) d ≡ d
  renameb-id Ib = refl
  renameb-id (x ⊗b y) = cong₂ _⊗b_ (renameb-id x) (renameb-id y)
  renameb-id (ext c) = cong ext (rename∂-id c)

mutual
  rename∂-compose
    : ∀ {ℓ} {Sig₁ Sig₂ Sig₃ : LogOSSignature ℓ}
      (σ : SigHom Sig₁ Sig₂)
      (τ : SigHom Sig₂ Sig₃)
      (c : Con∂ Sig₁)
    → rename∂ (composeSigHom σ τ) c ≡ rename∂ τ (rename∂ σ c)
  rename∂-compose σ τ I∂ = refl
  rename∂-compose σ τ (x ⊗∂ y) =
    cong₂ _⊗∂_ (rename∂-compose σ τ x) (rename∂-compose σ τ y)
  rename∂-compose σ τ (bnd d) = cong bnd (renameb-compose σ τ d)
  rename∂-compose σ τ (atom∂ _) = refl

  renameb-compose
    : ∀ {ℓ} {Sig₁ Sig₂ Sig₃ : LogOSSignature ℓ}
      (σ : SigHom Sig₁ Sig₂)
      (τ : SigHom Sig₂ Sig₃)
      (d : Conb Sig₁)
    → renameb (composeSigHom σ τ) d ≡ renameb τ (renameb σ d)
  renameb-compose σ τ Ib = refl
  renameb-compose σ τ (x ⊗b y) =
    cong₂ _⊗b_ (renameb-compose σ τ x) (renameb-compose σ τ y)
  renameb-compose σ τ (ext c) = cong ext (rename∂-compose σ τ c)
