{-
LogOS: a prototype Agda library for modular dynamic logic systems synthesized by AI
Copyright (C) 2026 AI.IMPACT GmbH
SPDX-License-Identifier: GPL-3.0-only
-}

{-# OPTIONS --safe #-}
module LogOS.Domain.Opacity.HasseObservableClass where

open import LogOS.Prelude
open import LogOS.Prelude using (Σ; _,_)

open import LogOS.Domain.Opacity.NumberTheory.LFunction.Riemann using (RiemannSpectral)
open import LogOS.Domain.Opacity.NumberTheory.LFunction.ZerosPack using (GRH_Without_Vacuity_Guards)

import LogOS.Theorems.Meta.TruthPositivity as TP
import LogOS.Domain.Opacity.WeilCriterionLedger as WCL

-- Hasse-regulated observability (schema):
-- a family of tests generated from finite regulators (e.g. product-of-chains/Hasse data),
-- plus an observer axiom that every such generated test is observable.
--
-- Key design choice: membership in the generated class is stated up to a chosen
-- test relation `_≈_` on tests. In code-based instantiations, `_≈_` is intended
-- to be decoded mutual refinement (in the boundary preorder), so
-- downstream lemmas only need decoded mutual refinement rather than literal code equality.

record HasseObservableClass {ℓT ℓW ℓObs ℓ≈ : Level}
                            (TPo : TP.TruthPositivity {ℓT} {ℓW} {ℓObs})
                            : Set (lsuc (ℓT ⊔ ℓW ⊔ ℓObs ⊔ ℓ≈)) where
  open TP.TruthPositivity TPo
  infix 4 _⊑_
  field
    -- Primitive notion: test refinement (a preorder, not necessarily antisymmetric).
    _⊑_ : Test → Test → Set ℓ≈

    Reg    : Set ℓT
    mkTest : Reg → Test

    -- Observer axiom: any regulator-generated test is observable.
    mkTest-observable : ∀ r → Observable (mkTest r)

  -- Derived: mutual refinement (the only meaning of `≈`).
  infix 4 _≈_
  _≈_ : Test → Test → Set ℓ≈
  t ≈ u = (t ⊑ u) × (u ⊑ t)

  field
    -- Observability respects mutual refinement.
    obs-resp : ∀ {t u} → t ≈ u → Observable t → Observable u

  -- The induced “generated by a regulator” class.
  Class : Test → Set (ℓT ⊔ ℓ≈)
  Class t = Σ Reg (λ r → mkTest r ≈ t)

  -- Terminology alias: “stable” tests are exactly the regulator-generated ones.
  Stable : Test → Set (ℓT ⊔ ℓ≈)
  Stable = Class

  class→Observable : ∀ {t} → Class t → Observable t
  class→Observable (r , rel) = obs-resp rel (mkTest-observable r)

  stable→Observable : ∀ {t} → Stable t → Observable t
  stable→Observable = class→Observable

  ObservableClass : WCL.ObservableClass {ℓCls = (ℓT ⊔ ℓ≈)} TPo
  ObservableClass = record
    { Class            = Class
    ; class→Observable = class→Observable
    }

-- If Weil probes factor through the Hasse generator on nontrivial zeros, GRH_Without_Vacuity_Guards follows.

probe-in-class-fromFactor
  : ∀ {ℓT ℓW ℓObs ℓ≈}
    {TPo : TP.TruthPositivity {ℓT} {ℓW} {ℓObs}}
    (HOC : HasseObservableClass {ℓ≈ = ℓ≈} TPo)
    {RS  : RiemannSpectral}
    (WC  : WCL.WeilCriterionWeak RS TPo)
    (sel : ∀ s → RiemannSpectral.NontrivialZero RS s → HasseObservableClass.Reg HOC)
    (mkTest∘sel≈probe
      : ∀ s (nz : RiemannSpectral.NontrivialZero RS s)
        → HasseObservableClass._≈_ HOC (HasseObservableClass.mkTest HOC (sel s nz))
                                      (WCL.WeilCriterionWeak.probe WC s))
  → ∀ s → RiemannSpectral.NontrivialZero RS s
        → HasseObservableClass.Class HOC (WCL.WeilCriterionWeak.probe WC s)
probe-in-class-fromFactor HOC WC sel mkTest∘sel≈probe s nz =
  (sel s nz , mkTest∘sel≈probe s nz)

GRH_Without_Vacuity_Guards-from-weak-criterion+Hasse
  : ∀ {ℓT ℓW ℓObs ℓ≈}
    (RS  : RiemannSpectral)
    (TPo : TP.TruthPositivity {ℓT} {ℓW} {ℓObs})
    (WC  : WCL.WeilCriterionWeak RS TPo)
    (HOC : HasseObservableClass {ℓ≈ = ℓ≈} TPo)
    (probe-in-class : ∀ s → RiemannSpectral.NontrivialZero RS s
                        → HasseObservableClass.Class HOC (WCL.WeilCriterionWeak.probe WC s))
  → GRH_Without_Vacuity_Guards RS
GRH_Without_Vacuity_Guards-from-weak-criterion+Hasse RS TPo WC HOC probe-in-class =
  WCL.GRH_Without_Vacuity_Guards-from-weak-criterion+class RS TPo WC
    (HasseObservableClass.ObservableClass HOC)
    probe-in-class
