#!/usr/bin/env bash
# LogOS: a host-minimal Agda library for modular dynamic logic systems synthesized by AI
# Copyright (C) 2026 AI.IMPACT GmbH
# SPDX-License-Identifier: GPL-3.0-only

set -euo pipefail

CHECK_NAME="check-integration-agda"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/check_common.sh
source "${SCRIPT_DIR}/lib/check_common.sh"

die() { check_die "${CHECK_NAME}" "$*"; }

LIB_ROOT="$(check_repo_root "${BASH_SOURCE[0]}")"

cd "${LIB_ROOT}"

AGDA="${AGDA:-agda}"
AGDA_FLAGS_BASE="${AGDA_FLAGS_BASE:---no-libraries -i . --safe --without-K}"
AGDA_FLAGS="${AGDA_FLAGS:-${AGDA_FLAGS_BASE}}"
AGDA_WARN_FLAGS="${AGDA_WARN_FLAGS:--W all -W error}"

AGDA_WARN_FLAGS="${AGDA_WARN_FLAGS//--W /-W }"

check_require_cmd "${CHECK_NAME}" rg

require_no_with_k "${CHECK_NAME}" "${AGDA_FLAGS}"

BUILD_DIR="_build/CheckIntegration"
MODULE_FILE="${BUILD_DIR}/AllIntegrationAgda.agda"
MODULE_LIST="${BUILD_DIR}/AllIntegrationAgda.modules"

mkdir -p "${BUILD_DIR}"
: > "${MODULE_LIST}"

while IFS= read -r -d '' f; do
  f="${f#./}"
  mod="${f%.agda}"
  mod="${mod//\//.}"
  printf '%s\n' "${mod}" >> "${MODULE_LIST}"
done < <(
  rg --files -0 --hidden --no-ignore LogOS/Apps LogOS/Adapters LogOS/Ports/Discipline \
    --glob '*.agda' \
    --glob '!_build/**' \
    --glob '!__MACOSX/**' \
    --glob '!**/._*' \
    --glob '!.git/**' \
    --glob '!.agda/**'
)

while IFS= read -r -d '' extra; do
  mod="${extra%.agda}"
  mod="${mod//\//.}"
  printf '%s\n' "${mod}" >> "${MODULE_LIST}"
done < <(
  rg --files -0 --hidden --no-ignore LogOS \
    --glob '**/Definitional/**/*.agda' \
    --glob '**/Strictification/**/*.agda' \
    --glob '**/*Definitional.agda' \
    --glob '**/*Strictification*.agda' \
    --glob '!_build/**' \
    --glob '!__MACOSX/**' \
    --glob '!**/._*' \
    --glob '!.git/**' \
    --glob '!.agda/**'
)

# Optional heavy reachability roots stay under `LogOS/Checks/**`, but they are
# integration-tier policy checks rather than core mathematical APIs.
extra="LogOS/Checks/Reachability/Ports.agda"
if [[ -f "${extra}" ]]; then
  mod="${extra%.agda}"
  mod="${mod//\//.}"
  printf '%s\n' "${mod}" >> "${MODULE_LIST}"
fi

extra="LogOS/API/Ports/PhysicalOptional.agda"
if [[ -f "${extra}" ]]; then
  mod="${extra%.agda}"
  mod="${mod//\//.}"
  printf '%s\n' "${mod}" >> "${MODULE_LIST}"
fi

extra="LogOS/Checks/PortStackUniquePublic.agda"
if [[ -f "${extra}" ]]; then
  mod="${extra%.agda}"
  mod="${mod//\//.}"
  printf '%s\n' "${mod}" >> "${MODULE_LIST}"
fi

if [[ ! -s "${MODULE_LIST}" ]]; then
  die "no integration .agda files found"
fi

sort -u "${MODULE_LIST}" -o "${MODULE_LIST}"

INCLUDE_RE="${AGDA_CHECK_INCLUDE_RE:-}"
EXCLUDE_RE="${AGDA_CHECK_EXCLUDE_RE:-}"
if [[ -n "${INCLUDE_RE}" ]]; then
  MODULE_LIST_FILTERED="${MODULE_LIST}.include"
  : > "${MODULE_LIST_FILTERED}"
  rg -N "${INCLUDE_RE}" "${MODULE_LIST}" >> "${MODULE_LIST_FILTERED}" || true
  mv "${MODULE_LIST_FILTERED}" "${MODULE_LIST}"
fi
if [[ -n "${EXCLUDE_RE}" ]]; then
  MODULE_LIST_FILTERED="${MODULE_LIST}.exclude"
  : > "${MODULE_LIST_FILTERED}"
  rg -N -v "${EXCLUDE_RE}" "${MODULE_LIST}" >> "${MODULE_LIST_FILTERED}" || true
  mv "${MODULE_LIST_FILTERED}" "${MODULE_LIST}"
fi

if [[ ! -s "${MODULE_LIST}" ]]; then
  die "no integration modules remain after filtering"
fi

MODULE_LIST_ORDERED="${MODULE_LIST}.ordered"
: > "${MODULE_LIST_ORDERED}"
rg -N -v "\\.All$" "${MODULE_LIST}" >> "${MODULE_LIST_ORDERED}" || true
rg -N "\\.All$" "${MODULE_LIST}" >> "${MODULE_LIST_ORDERED}" || true
mv "${MODULE_LIST_ORDERED}" "${MODULE_LIST}"

cat > "${MODULE_FILE}" <<'EOF'
-- Auto-generated by scripts/check_integration_agda.sh. Do not edit.
module CheckIntegration.AllIntegrationAgda where
EOF

while IFS= read -r mod; do
  printf 'import %s\n' "${mod}" >> "${MODULE_FILE}"
done < "${MODULE_LIST}"

read -r -a agda_flags <<< "${AGDA_FLAGS}"
read -r -a agda_warn_flags <<< "${AGDA_WARN_FLAGS}"

if [[ "${AGDA_TELEMETRY:-}" == "1" ]]; then
  TS="$(date +%Y%m%d_%H%M%S)"
  TELE_DIR="${AGDA_TELEMETRY_DIR:-_build/telemetry}"
  TELE_OUT="${TELE_DIR}/${CHECK_NAME}_${TS}.modules.tsv"
  bash "${SCRIPT_DIR}/lib/run_agda_with_telemetry.sh" "${TELE_OUT}" -- \
    "${AGDA}" "${agda_flags[@]}" -i _build "${agda_warn_flags[@]}" "${MODULE_FILE}"
else
  "${AGDA}" "${agda_flags[@]}" -i _build "${agda_warn_flags[@]}" "${MODULE_FILE}"
fi
