#!/usr/bin/env bash
# LogOS: a prototype Agda library for modular dynamic logic systems synthesized by AI
# Copyright (C) 2026 AI.IMPACT GmbH
# SPDX-License-Identifier: GPL-3.0-only

set -euo pipefail

CHECK_NAME="check-all-docs"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/check_common.sh
source "${SCRIPT_DIR}/lib/check_common.sh"

die() { check_die "${CHECK_NAME}" "$*"; }

LIB_ROOT="$(check_repo_root "${BASH_SOURCE[0]}")"

cd "${LIB_ROOT}"

AGDA="${AGDA:-agda}"
AGDA_FLAGS="${AGDA_FLAGS:---no-libraries -i . --safe}"
AGDA_WARN_FLAGS="${AGDA_WARN_FLAGS:--W all -W noCoverageNoExactSplit -W error}"

check_require_cmd "${CHECK_NAME}" rg

BUILD_DIR="_build/CheckAll"
MODULE_FILE="${BUILD_DIR}/AllDocs.agda"
MODULE_LIST="${BUILD_DIR}/AllDocs.modules"

mkdir -p "${BUILD_DIR}"
: > "${MODULE_LIST}"

while IFS= read -r -d '' f; do
  f="${f#./}"
  mod="${f%.lagda.md}"
  mod="${mod//\//.}"
  printf '%s\n' "${mod}" >> "${MODULE_LIST}"
done < <(
  rg --files -0 --hidden \
    --glob '*.lagda.md' \
    --glob '!_build/**' \
    --glob '!.git/**' \
    --glob '!.agda/**'
)

if [[ ! -s "${MODULE_LIST}" ]]; then
  die "no .lagda.md files found"
fi

sort -u "${MODULE_LIST}" -o "${MODULE_LIST}"

cat > "${MODULE_FILE}" <<'EOF'
-- Auto-generated by scripts/check_all_docs.sh. Do not edit.
module CheckAll.AllDocs where
EOF

while IFS= read -r mod; do
  printf 'import %s\n' "${mod}" >> "${MODULE_FILE}"
done < "${MODULE_LIST}"

read -r -a agda_flags <<< "${AGDA_FLAGS}"
read -r -a agda_warn_flags <<< "${AGDA_WARN_FLAGS}"

"${AGDA}" "${agda_flags[@]}" -i _build "${agda_warn_flags[@]}" "${MODULE_FILE}"
