#!/usr/bin/env bash
# LogOS: an Agda research library for foundational logic system architecture.
# Copyright (C) 2026 AI.IMPACT GmbH
# SPDX-License-Identifier: GPL-3.0-only

set -euo pipefail

die() {
  echo "check-all-agda: $*" >&2
  exit 1
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "${LIB_ROOT}"

AGDA="${AGDA:-agda}"
AGDA_FLAGS="${AGDA_FLAGS:---no-libraries -i .}"
AGDA_WARN_FLAGS="${AGDA_WARN_FLAGS:--W all -W error}"

BUILD_DIR="_build/CheckAll"
MODULE_FILE="${BUILD_DIR}/AllAgda.agda"
MODULE_LIST="${BUILD_DIR}/AllAgda.modules"

mkdir -p "${BUILD_DIR}"
: > "${MODULE_LIST}"

if command -v rg >/dev/null 2>&1; then
  while IFS= read -r -d '' f; do
    f="${f#./}"
    mod="${f%.agda}"
    mod="${mod//\//.}"
    printf '%s\n' "${mod}" >> "${MODULE_LIST}"
  done < <(rg --files -0 -g '*.agda' -g '!_build/**')
else
  while IFS= read -r -d '' f; do
    f="${f#./}"
    mod="${f%.agda}"
    mod="${mod//\//.}"
    printf '%s\n' "${mod}" >> "${MODULE_LIST}"
  done < <(find . -type f -name '*.agda' -not -path './_build/*' -print0)
fi

if [[ ! -s "${MODULE_LIST}" ]]; then
  die "no .agda files found"
fi

sort -u "${MODULE_LIST}" -o "${MODULE_LIST}"

cat > "${MODULE_FILE}" <<'EOF'
-- Auto-generated by scripts/check_all_agda.sh. Do not edit.
module CheckAll.AllAgda where
EOF

while IFS= read -r mod; do
  printf 'import %s\n' "${mod}" >> "${MODULE_FILE}"
done < "${MODULE_LIST}"

read -r -a agda_flags <<< "${AGDA_FLAGS}"
read -r -a agda_warn_flags <<< "${AGDA_WARN_FLAGS}"

"${AGDA}" "${agda_flags[@]}" -i _build "${agda_warn_flags[@]}" "${MODULE_FILE}"
