#!/usr/bin/env bash
# LogOS: a host-minimal Agda library for modular dynamic logic systems synthesized by AI
# Copyright (C) 2026 AI.IMPACT GmbH
# SPDX-License-Identifier: GPL-3.0-only

set -euo pipefail

CHECK_NAME="check-core-agda"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/check_common.sh
source "${SCRIPT_DIR}/lib/check_common.sh"

die() { check_die "${CHECK_NAME}" "$*"; }

LIB_ROOT="$(check_repo_root "${BASH_SOURCE[0]}")"

cd "${LIB_ROOT}"

AGDA="${AGDA:-agda}"
AGDA_FLAGS_BASE="${AGDA_FLAGS_BASE:---no-libraries -i . --safe --without-K}"
AGDA_FLAGS="${AGDA_FLAGS:-${AGDA_FLAGS_BASE}}"
AGDA_WARN_FLAGS="${AGDA_WARN_FLAGS:--W all -W error}"

AGDA_WARN_FLAGS="${AGDA_WARN_FLAGS//--W /-W }"

check_require_cmd "${CHECK_NAME}" rg

require_no_with_k "${CHECK_NAME}" "${AGDA_FLAGS}"

BUILD_DIR="_build/CheckCore"
MODULE_FILE="${BUILD_DIR}/AllCoreAgda.agda"
MODULE_LIST="${BUILD_DIR}/AllCoreAgda.modules"

mkdir -p "${BUILD_DIR}"
: > "${MODULE_LIST}"

while IFS= read -r -d '' f; do
  f="${f#./}"
  mod="${f%.agda}"
  mod="${mod//\//.}"
  printf '%s\n' "${mod}" >> "${MODULE_LIST}"
done < <(
  rg --files -0 --hidden --no-ignore \
    --glob '*.agda' \
    --glob '!LogOS/Apps/**' \
    --glob '!LogOS/Adapters/**' \
    --glob '!LogOS/**/Definitional/**' \
    --glob '!LogOS/**/Strictification/**' \
    --glob '!LogOS/**/*Definitional.agda' \
    --glob '!LogOS/**/*Strictification*.agda' \
    --glob '!LogOS/API/Ports/PhysicalOptional.agda' \
    --glob '!LogOS/Ports/AbstractLandauer2Cat.agda' \
    --glob '!LogOS/Ports/AbstractLandauer2Cat/**' \
    --glob '!LogOS/Ports/AbstractLandauerObservational.agda' \
    --glob '!LogOS/Ports/AbstractDeutsch2Cat.agda' \
    --glob '!LogOS/Ports/AbstractDeutsch2Cat/**' \
    --glob '!LogOS/Ports/AbstractDeutschLandauer2Cat.agda' \
    --glob '!LogOS/Ports/AbstractDeutschLandauer2Cat/**' \
    --glob '!LogOS/Ports/AbstractDeutschNoCloning.agda' \
    --glob '!LogOS/Ports/PreQuantum/**' \
    --glob '!LogOS/Ports/Discipline/**' \
    --glob '!LogOS/Ports/**/Definitional.agda' \
    --glob '!LogOS/Checks/PortStackUniquePublic.agda' \
    --glob '!LogOS/Checks/Reachability/Ports.agda' \
    --glob '!_build/**' \
    --glob '!__MACOSX/**' \
    --glob '!**/._*' \
    --glob '!.git/**' \
    --glob '!.agda/**'
)

if [[ ! -s "${MODULE_LIST}" ]]; then
  die "no core .agda files found"
fi

sort -u "${MODULE_LIST}" -o "${MODULE_LIST}"

cat > "${MODULE_FILE}" <<'EOF'
-- Auto-generated by scripts/check_core_agda.sh. Do not edit.
module CheckCore.AllCoreAgda where
EOF

while IFS= read -r mod; do
  printf 'import %s\n' "${mod}" >> "${MODULE_FILE}"
done < "${MODULE_LIST}"

read -r -a agda_flags <<< "${AGDA_FLAGS}"
read -r -a agda_warn_flags <<< "${AGDA_WARN_FLAGS}"

bash "${SCRIPT_DIR}/lib/warm_builtin_nat.sh" \
  "${AGDA}" "${AGDA_FLAGS}" "${AGDA_WARN_FLAGS}" "${BUILD_DIR}" "CheckCore"

if [[ "${AGDA_TELEMETRY:-}" == "1" ]]; then
  TS="$(date +%Y%m%d_%H%M%S)"
  TELE_DIR="${AGDA_TELEMETRY_DIR:-_build/telemetry}"
  TELE_OUT="${TELE_DIR}/${CHECK_NAME}_${TS}.modules.tsv"
  bash "${SCRIPT_DIR}/lib/run_agda_with_telemetry.sh" "${TELE_OUT}" -- \
    "${AGDA}" "${agda_flags[@]}" -i _build "${agda_warn_flags[@]}" "${MODULE_FILE}"
else
  "${AGDA}" "${agda_flags[@]}" -i _build "${agda_warn_flags[@]}" "${MODULE_FILE}"
fi
