#!/usr/bin/env bash
# LogOS: models for AI-driven, human-on-the-loop, machine-checked formal reasoning
# Copyright (C) 2026 AI.IMPACT GmbH
# SPDX-License-Identifier: GPL-3.0-only

set -euo pipefail

OUT_DIR="${1:-}"
if [[ -z "${OUT_DIR}" ]]; then
  echo "usage: write_html_index.sh <html-dir>" >&2
  exit 2
fi

mkdir -p "${OUT_DIR}"

cat > "${OUT_DIR}/index.html" <<'EOF'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>LogOS (Agda) — Docs</title>
    <link rel="stylesheet" href="Agda.css" />
  </head>
  <body>
    <main style="max-width: 56rem; margin: 2rem auto; padding: 0 1rem; font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif;">
      <h1>LogOS (Agda) — Docs</h1>
      <p>Generated by Agda’s HTML backend.</p>
      <ul>
        <li><a href="docs.Library.html">Library overview</a></li>
        <li><a href="docs.LogOS_Overview.html">Start here: overview</a></li>
        <li><a href="docs.DeepDive.Architecture_PortsAdapters.html">Architecture: ports/adapters</a></li>
        <li><a href="docs.LogOS_Core_Spec.html">Specification (records/laws)</a></li>
        <li><a href="docs.Applications.ZFC.html">Application: ZFC</a></li>
        <li><a href="docs.Applications.InfoTheory.html">Application: InfoTheory</a></li>
        <li><a href="docs.Applications.Universality.html">Application: universality</a></li>
        <li><a href="docs.Applications.Complexity.html">Application: complexity</a></li>
        <li><a href="docs.Applications.Opacity.html">Application: opacity</a></li>
        <li><a href="docs.Applications.Agents.html">Application: agents</a></li>
        <li><a href="docs.DeepDive.CoreScience.html">DeepDive: core science</a></li>
        <li><a href="docs.DeepDive.Communication.html">DeepDive: communication</a></li>
        <li><a href="docs.DeepDive.AIAssistedModeling.html">DeepDive: AI-assisted modeling</a></li>
        <li><a href="docs.DeepDive.PLSpine.html">DeepDive: PL spine</a></li>
        <li><a href="docs.DeepDive.ZFC_Demo.html">DeepDive: ZFC demo</a></li>
        <li><a href="docs.DeepDive.Complexity.html">DeepDive: complexity</a></li>
        <li><a href="docs.Views.All.html">Views: one kernel, many readings</a></li>
      </ul>
    </main>
  </body>
</html>
EOF

touch "${OUT_DIR}/.nojekyll"
