{-
LogOS: an Agda Library for foundational logic architecture
Copyright (C) 2025 AI.IMPACT GmbH
SPDX-License-Identifier: GPL-3.0-only
-}

{-# OPTIONS --safe #-}
module LogOS.Free.Constraints where

open import LogOS.Prelude
open import Data.Product using (_×_; _,_)
open import Data.Nat using (ℕ)
open import LogOS.Prelude as Eq using (refl; trans; cong; cong₂)

open import LogOS.Minimal.Con
open import LogOS.Minimal.Adjunction
open import LogOS.Algebra.ConAlg
import LogOS.Algebra.ConAlg as Alg

-- Syntax for free constraint algebra with two sorts (boundary, bulk)

infixl 7 _⊗∂_ _⊗b_
infix 4 _≤∂_ _≤b_

mutual
  data Con∂ {ℓ : Level} : Set ℓ where
    I∂   : Con∂ {ℓ}
    _⊗∂_ : Con∂ {ℓ} → Con∂ {ℓ} → Con∂ {ℓ}
    bnd  : Conb {ℓ} → Con∂ {ℓ}

  data Conb {ℓ : Level} : Set ℓ where
    Ib   : Conb {ℓ}
    _⊗b_ : Conb {ℓ} → Conb {ℓ} → Conb {ℓ}
    ext  : Con∂ {ℓ} → Conb {ℓ}

-- Preorders generated by lax laws and monoidal congruence

mutual
  data _≤∂_ {ℓ : Level} : Con∂ {ℓ} → Con∂ {ℓ} → Set ℓ where
    refl∂  : ∀ {x} → x ≤∂ x
    trans∂ : ∀ {x y z} → x ≤∂ y → y ≤∂ z → x ≤∂ z
    cong⊗∂ : ∀ {x x' y y'} → x ≤∂ x' → y ≤∂ y' → (Con∂._⊗∂_ x y) ≤∂ (Con∂._⊗∂_ x' y')
    unitbnd : ∀ {c} → c ≤∂ Con∂.bnd (Conb.ext c)
    bnd-⊗  : ∀ {x y} → Con∂.bnd (Conb._⊗b_ x y) ≤∂ (Con∂._⊗∂_ (Con∂.bnd x) (Con∂.bnd y))
    bnd-I  : Con∂.bnd Conb.Ib ≤∂ Con∂.I∂

  data _≤b_ {ℓ : Level} : Conb {ℓ} → Conb {ℓ} → Set ℓ where
    reflb  : ∀ {x} → x ≤b x
    transb : ∀ {x y z} → x ≤b y → y ≤b z → x ≤b z
    cong⊗b : ∀ {x x' y y'} → x ≤b x' → y ≤b y' → (Conb._⊗b_ x y) ≤b (Conb._⊗b_ x' y')
    counit : ∀ {d} → Conb.ext (Con∂.bnd d) ≤b d
    ext-⊗ : ∀ {x y} → Conb.ext (Con∂._⊗∂_ x y) ≤b (Conb._⊗b_ (Conb.ext x) (Conb.ext y))
    ext-I : Conb.ext Con∂.I∂ ≤b Conb.Ib

-- Build ConPoset/Monoidal/LaxAdjunction from syntax

conPoset∂ : ∀ {ℓ} → ConPoset ℓ
conPoset∂ {ℓ} = record { Con = Con∂ {ℓ} ; _⊑_ = _≤∂_ ; refl = refl∂ ; trans = trans∂ }

conPosetb : ∀ {ℓ} → ConPoset ℓ
conPosetb {ℓ} = record { Con = Conb {ℓ} ; _⊑_ = _≤b_ ; refl = reflb ; trans = transb }

BBfree : ∀ {ℓ} → BulkBoundary ℓ
BBfree {ℓ} = record { bulk = conPosetb {ℓ} ; bnd = conPoset∂ {ℓ} }

MBulkfree : ∀ {ℓ} → MonoidalPoset (BulkBoundary.bulk (BBfree {ℓ}))
MBulkfree = record
  { _⊗_ = _⊗b_
  ; I   = Ib
  ; mono⊗ = λ {x} {x'} {y} {y'} px py → cong⊗b px py
  }

MBndfree : ∀ {ℓ} → MonoidalPoset (BulkBoundary.bnd (BBfree {ℓ}))
MBndfree = record
  { _⊗_ = _⊗∂_
  ; I   = I∂
  ; mono⊗ = λ {x} {x'} {y} {y'} px py → cong⊗∂ px py
  }

Holofree : ∀ {ℓ} → LaxMonoidalAdjunction (BBfree {ℓ}) (MBulkfree {ℓ}) (MBndfree {ℓ})
Holofree = record
  { core = record
      { ext = ext
      ; bnd = bnd
      ; unit-lax   = λ c → unitbnd
      ; counit-lax = λ d → counit
      }
  ; ext-⊗-lax = λ x y → ext-⊗
  ; ext-I-lax  = ext-I
  ; bnd-⊗-lax  = λ x y → bnd-⊗
  ; bnd-I-lax  = bnd-I
  }

FreeConAlg : ∀ {ℓ} → ConAlg {ℓ}
FreeConAlg = record { BB = BBfree ; MBulk = MBulkfree ; MBnd = MBndfree ; Holo = Holofree }

-- Initiality: unique hom from FreeConAlg to any ConAlg, up to pointwise ≤

mutual
  interp∂ : ∀ {ℓ} (A : ConAlg {ℓ}) → Con∂ {ℓ} → ConAlg.Con_bnd A
  interp∂ A I∂ = ConAlg.I∂ A
  interp∂ A (x ⊗∂ y) = ConAlg._⊗∂_ A (interp∂ A x) (interp∂ A y)
  interp∂ A (Con∂.bnd d) = LaxMonoidalAdjunction.bnd (ConAlg.Holo A) (interpb A d)

  interpb : ∀ {ℓ} (A : ConAlg {ℓ}) → Conb {ℓ} → ConAlg.Con_bulk A
  interpb A Ib = ConAlg.Ib A
  interpb A (x ⊗b y) = ConAlg._⊗b_ A (interpb A x) (interpb A y)
  interpb A (ext c) = ConAlg.ext A (interp∂ A c)

-- Monotonicity of interpretation

mutual
  interp∂-mono : ∀ {ℓ} (A : ConAlg {ℓ}) {x y} → x ≤∂ y →
                  ConAlg._⊑bnd_ A (interp∂ A x) (interp∂ A y)
  interp∂-mono A refl∂ = ConPoset.refl (BulkBoundary.bnd (ConAlg.BB A))
  interp∂-mono A (trans∂ p q) =
    ConPoset.trans (BulkBoundary.bnd (ConAlg.BB A)) (interp∂-mono A p) (interp∂-mono A q)
  interp∂-mono A (cong⊗∂ px py) =
    let open MonoidalPoset (ConAlg.MBnd A) in
    mono⊗ (interp∂-mono A px) (interp∂-mono A py)
  interp∂-mono A unitbnd = LaxMonoidalAdjunction.unit-lax (ConAlg.Holo A) _
  interp∂-mono A bnd-⊗   = LaxMonoidalAdjunction.bnd-⊗-lax (ConAlg.Holo A) _ _
  interp∂-mono A bnd-I   = LaxMonoidalAdjunction.bnd-I-lax (ConAlg.Holo A)

  interpb-mono : ∀ {ℓ} (A : ConAlg {ℓ}) {x y} → x ≤b y →
                  ConAlg._⊑bulk_ A (interpb A x) (interpb A y)
  interpb-mono A reflb = ConPoset.refl (BulkBoundary.bulk (ConAlg.BB A))
  interpb-mono A (transb p q) =
    ConPoset.trans (BulkBoundary.bulk (ConAlg.BB A)) (interpb-mono A p) (interpb-mono A q)
  interpb-mono A (cong⊗b px py) =
    let open MonoidalPoset (ConAlg.MBulk A) in
    mono⊗ (interpb-mono A px) (interpb-mono A py)
  interpb-mono A counit = LaxMonoidalAdjunction.counit-lax (ConAlg.Holo A) _
  interpb-mono A ext-⊗  = LaxMonoidalAdjunction.ext-⊗-lax (ConAlg.Holo A) _ _
  interpb-mono A ext-I  = LaxMonoidalAdjunction.ext-I-lax (ConAlg.Holo A)

-- Build the universal hom Free → A

to : ∀ {ℓ} (A : ConAlg {ℓ}) → ConAlgHom FreeConAlg A
to A = record
  { map∂ = interp∂ A
  ; mapb = interpb A
  ; mono∂ = interp∂-mono A
  ; monob = interpb-mono A
  }

-- Strict fold: structure-preserving on-the-nose (for uniqueness)

fold≡ : ∀ {ℓ} (A : ConAlg {ℓ}) → ConAlgHom≡ FreeConAlg A
fold≡ A = record
  { map∂ = interp∂ A
  ; mapb = interpb A
  ; unit∂ = refl
  ; unitb = refl
  ; ten∂  = λ _ _ → refl
  ; tenb  = λ _ _ → refl
  ; ext-comm = λ _ → refl
  ; bnd-comm = λ _ → refl
  }

-- (Optional) enriched uniqueness up to preorder can be added per‑model.

-- Initial object interface for ConAlg (up to preorder enrichment)

record InitialConAlg {ℓ : Level} : Set (lsuc (lsuc ℓ)) where
  field
    Free     : ConAlg {ℓ}
    fold     : ∀ (A : ConAlg {ℓ}) → ConAlgHom≡ Free A
    unique   : ∀ (A : ConAlg {ℓ}) (h : ConAlgHom≡ Free A) →
               (∀ x → ConAlgHom≡.map∂ (fold A) x ≡ ConAlgHom≡.map∂ h x) ×
               (∀ d → ConAlgHom≡.mapb (fold A) d ≡ ConAlgHom≡.mapb h d)

initialConAlg : ∀ {ℓ} → InitialConAlg {ℓ}
-- Helper for the uniqueness proof (moved out to support a where mutual block)
uniqueProof : ∀ {ℓ} (A : ConAlg {ℓ}) (h : ConAlgHom≡ FreeConAlg A) →
              (∀ x → ConAlgHom≡.map∂ (fold≡ A) x ≡ ConAlgHom≡.map∂ h x) ×
              (∀ d → ConAlgHom≡.mapb (fold≡ A) d ≡ ConAlgHom≡.mapb h d)
uniqueProof A h = (λ x → uniq∂ x) , (λ d → uniqb d)
  where
    open ConAlgHom≡ h using (map∂; mapb; unit∂; unitb; ten∂; tenb; ext-comm; bnd-comm)
    open ConAlg A
    mutual
      uniq∂ : (x : Con∂) → interp∂ A x ≡ map∂ x
      uniq∂ I∂ = sym unit∂
      uniq∂ (Con∂._⊗∂_ x y) =
        Eq.trans (cong₂ (ConAlg._⊗∂_ A) (uniq∂ x) (uniq∂ y)) (sym (ten∂ x y))
      uniq∂ (Con∂.bnd d) =
        Eq.trans (cong (LaxMonoidalAdjunction.bnd (ConAlg.Holo A)) (uniqb d)) (sym (bnd-comm d))

      uniqb : (d : Conb) → interpb A d ≡ mapb d
      uniqb Ib = sym unitb
      uniqb (Conb._⊗b_ x y) =
        Eq.trans (cong₂ (ConAlg._⊗b_ A) (uniqb x) (uniqb y)) (sym (tenb x y))
      uniqb (Conb.ext c) =
        Eq.trans (cong (LaxMonoidalAdjunction.ext (ConAlg.Holo A)) (uniq∂ c)) (sym (ext-comm c))

initialConAlg = record
  { Free  = FreeConAlg
  ; fold  = fold≡
  ; unique = uniqueProof
  }
